import { createFileRoute } from "@tanstack/react-router";
import { NavRail } from "@/components/NavRail";
import { SCORES, SCORE_META, STORIES, quantumReadiness, type Scores } from "@/lib/sentinelx";
import { TrendingUp, ShieldCheck, AlertTriangle, IndianRupee, Timer, Sparkles, GitBranch } from "lucide-react";

const COMPLIANCE = [
  { std: "PCI DSS v4.0",             status: "aligned",     note: "Reqs 3, 4, 8, 10 mapped to Trust Fabric" },
  { std: "ISO 27001",                status: "aligned",     note: "A.5, A.8, A.12, A.16 automated evidence" },
  { std: "RBI Cyber Framework",      status: "aligned",     note: "SOC-2 incident clock ≤ 6h" },
  { std: "DPDP Act 2023",            status: "aligned",     note: "Data-principal audit ledger + purpose tags" },
  { std: "NIST PQC (FIPS 203/204)",  status: "in-progress", note: "Kyber-1024 · Dilithium-3 pilot" },
];

export const Route = createFileRoute("/executive")({
  head: () => ({
    meta: [
      { title: "Executive Brief · Kairos" },
      { name: "description", content: "Board-ready daily brief: composite trust, top risks, business impact and PQC posture." },
      { property: "og:title", content: "Kairos · Executive Brief" },
      { property: "og:description", content: "One-page CISO / CFO brief generated by the Executive Decision Agent." },
    ],
  }),
  component: ExecPage,
});

function ExecPage() {
  const story = STORIES[0];
  const q = quantumReadiness();
  const order: (keyof Scores)[] = ["trust", "threat", "fraud", "quantum", "identity", "business", "operational"];
  return (
    <div className="min-h-screen">
      <NavRail />
      <div className="mx-auto max-w-[1400px] px-6 py-6">
        <div className="mb-4 flex items-end justify-between">
          <div>
            <div className="font-mono text-[10px] uppercase tracking-widest text-muted-foreground">
              Daily Executive Brief · 14 July 2026 · 06:00 IST
            </div>
            <h1 className="text-glow text-2xl font-semibold">Trust posture &amp; material risks</h1>
            <p className="mt-1 max-w-3xl text-sm text-muted-foreground">
              Generated by the Executive Decision Agent from 4.2 B events, 812 K entities and 47 active detections
              across the last 24h. Recipients: CISO, CRO, CFO, Head of Retail, RBI Nodal Officer.
            </p>
          </div>
          <div className="hidden items-center gap-2 rounded-md border border-primary/30 bg-primary/10 px-3 py-1.5 font-mono text-[10px] uppercase tracking-widest text-primary md:flex">
            <Sparkles className="h-3.5 w-3.5" /> LLM summary · GPT-class · grounded on evidence graph
          </div>
        </div>

        <div className="grid grid-cols-12 gap-4">
          <div className="panel col-span-8 p-5">
            <div className="mb-3 flex items-center gap-2">
              <ShieldCheck className="h-4 w-4 text-primary" />
              <div className="font-mono text-[10px] uppercase tracking-widest text-muted-foreground">Overnight narrative</div>
            </div>
            <div className="space-y-3 text-[15px] leading-relaxed text-foreground/90">
              <p>
                Composite <span className="font-semibold text-[color:var(--cyber)]">Trust score dropped 4 points to 71</span>,
                driven by a single critical incident on the corporate SRE fleet. The Cyber Correlation Agent linked
                seven telemetry streams into one attack story <span className="font-mono text-xs text-muted-foreground">({story.id})</span>
                consistent with APT38 (<em>Lazarus</em>) staging a Harvest-Now-Decrypt-Later exfiltration.
              </p>
              <p>
                A 1.8 GB customer ledger export was staged inside an RSA-2048 archive on
                <span className="mx-1 font-mono text-xs">dev:kunal-lt</span> and egressed to a TOR exit attributed to
                Lazarus infrastructure. If the archive is captured today, a future cryptanalytically-relevant quantum
                computer would decrypt it. Rotating <span className="font-mono text-xs">cert:web-old</span> to
                <span className="font-mono text-xs"> Dilithium-3</span> — already staged in the Q3 PQC wave —
                <span className="font-semibold text-[color:var(--safe)]"> reduces 10-year business exposure by ~₹420 Cr</span>.
              </p>
              <p>
                Fraud Evolution Agent surfaced an emerging mule cluster (
                <span className="font-mono text-xs">acc:mule-77 → mer:offshore</span>) with velocity 5.6× baseline;
                autopilot has frozen payouts pending SOC L2 approval. No customer-facing outages. RBI 6-hour breach
                clock started at 05:14 IST for the staged data event.
              </p>
            </div>

            <div className="mt-5 grid grid-cols-4 gap-3">
              <Callout icon={<AlertTriangle className="h-3.5 w-3.5" />} tone="danger" label="Material incidents" value="1" hint="HNDL staging · critical" />
              <Callout icon={<IndianRupee  className="h-3.5 w-3.5" />} tone="warn"   label="Exposure avoided" value="₹420 Cr" hint="via PQC counterfactual" />
              <Callout icon={<Timer       className="h-3.5 w-3.5" />} tone="cyber"  label="Detection latency" value="42 s" hint="phish → attack story" />
              <Callout icon={<TrendingUp  className="h-3.5 w-3.5" />} tone="safe"   label="False-positive rate" value="0.6%" hint="↓ 78% vs legacy SIEM" />
            </div>
          </div>

          <div className="col-span-4 space-y-4">
            <div className="panel p-4">
              <div className="mb-3 font-mono text-[10px] uppercase tracking-widest text-muted-foreground">Composite scores</div>
              <div className="space-y-2">
                {order.map(k => {
                  const meta = SCORE_META[k];
                  const v = SCORES[k];
                  const color =
                    meta.hue === "danger" ? "var(--danger)" :
                    meta.hue === "warn"   ? "var(--warn)"   :
                    meta.hue === "safe"   ? "var(--safe)"   : "var(--cyber)";
                  return (
                    <div key={k} className="flex items-center gap-3">
                      <div className="w-28 text-xs text-muted-foreground">{meta.label}</div>
                      <div className="h-1.5 flex-1 overflow-hidden rounded-full bg-muted/40">
                        <div className="h-full" style={{ width: `${v}%`, background: color, boxShadow: `0 0 10px color-mix(in oklab, ${color} 60%, transparent)` }} />
                      </div>
                      <div className="w-8 text-right font-mono text-xs" style={{ color }}>{v}</div>
                    </div>
                  );
                })}
              </div>
            </div>

            <div className="panel p-4">
              <div className="mb-3 font-mono text-[10px] uppercase tracking-widest text-muted-foreground">Quantum posture</div>
              <div className="grid grid-cols-3 gap-2 text-center">
                <QCell label="PQC readiness" value={q.readiness} unit="%" tone="safe" />
                <QCell label="Harvest risk"   value={q.harvestRisk} unit="" tone="danger" />
                <QCell label="Migration"      value={q.migrationPriority} unit="%" tone="warn" />
              </div>
              <div className="mt-3 text-xs text-muted-foreground">
                40% of the encrypted estate still depends on RSA/ECC. Recommended next PQC wave targets
                swift-gateway, netbanking-mobile and the legacy ATM ring.
              </div>
            </div>

          </div>
        </div>

        {/* Compliance mapping — relocated from Architecture */}
        <section className="panel mt-4 p-5">
          <div className="mb-3 flex items-center gap-2 font-mono text-[10px] uppercase tracking-widest text-muted-foreground">
            <GitBranch className="h-3.5 w-3.5" /> Compliance mapping
          </div>
          <div className="grid gap-2 md:grid-cols-2 xl:grid-cols-5">
            {COMPLIANCE.map(c => (
              <div key={c.std} className="rounded-md border border-border/60 bg-card/40 p-3">
                <div className="flex items-center justify-between">
                  <span className="text-xs font-medium">{c.std}</span>
                  <span className={`rounded px-1.5 py-0.5 font-mono text-[9px] uppercase tracking-widest ${
                    c.status === "aligned" ? "bg-emerald-500/15 text-emerald-400" : "bg-amber-500/15 text-amber-400"
                  }`}>{c.status}</span>
                </div>
                <p className="mt-1 text-[11px] text-muted-foreground">{c.note}</p>
              </div>
            ))}
          </div>
        </section>
      </div>
    </div>
  );
}

function Callout({ icon, tone, label, value, hint }: { icon: React.ReactNode; tone: "safe" | "warn" | "danger" | "cyber"; label: string; value: string; hint: string }) {
  const color = tone === "danger" ? "var(--danger)" : tone === "warn" ? "var(--warn)" : tone === "safe" ? "var(--safe)" : "var(--cyber)";
  return (
    <div className="rounded-lg border border-border/60 bg-card/60 p-3">
      <div className="flex items-center gap-1.5 font-mono text-[10px] uppercase tracking-widest" style={{ color }}>
        {icon} {label}
      </div>
      <div className="mt-1 text-xl font-semibold" style={{ color }}>{value}</div>
      <div className="mt-0.5 text-[11px] text-muted-foreground">{hint}</div>
    </div>
  );
}

function QCell({ label, value, unit, tone }: { label: string; value: number; unit: string; tone: "safe" | "warn" | "danger" }) {
  const color = tone === "danger" ? "var(--danger)" : tone === "warn" ? "var(--warn)" : "var(--safe)";
  return (
    <div className="rounded-md border border-border/60 bg-muted/20 p-2">
      <div className="font-mono text-[9px] uppercase tracking-widest text-muted-foreground">{label}</div>
      <div className="mt-1 font-mono text-lg font-semibold" style={{ color }}>{value}{unit}</div>
    </div>
  );
}
