/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as ResponseRouteImport } from './routes/response'
import { Route as QuantumRouteImport } from './routes/quantum'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as GraphRouteImport } from './routes/graph'
import { Route as ExecutiveRouteImport } from './routes/executive'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const ResponseRoute = ResponseRouteImport.update({
  id: '/response',
  path: '/response',
  getParentRoute: () => rootRouteImport,
} as any)
const QuantumRoute = QuantumRouteImport.update({
  id: '/quantum',
  path: '/quantum',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphRoute = GraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecutiveRoute = ExecutiveRouteImport.update({
  id: '/executive',
  path: '/executive',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/executive': typeof ExecutiveRoute
  '/graph': typeof GraphRoute
  '/profile': typeof ProfileRoute
  '/quantum': typeof QuantumRoute
  '/response': typeof ResponseRoute
  '/stories': typeof StoriesRoute
  '/welcome': typeof WelcomeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/executive': typeof ExecutiveRoute
  '/graph': typeof GraphRoute
  '/profile': typeof ProfileRoute
  '/quantum': typeof QuantumRoute
  '/response': typeof ResponseRoute
  '/stories': typeof StoriesRoute
  '/welcome': typeof WelcomeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/executive': typeof ExecutiveRoute
  '/graph': typeof GraphRoute
  '/profile': typeof ProfileRoute
  '/quantum': typeof QuantumRoute
  '/response': typeof ResponseRoute
  '/stories': typeof StoriesRoute
  '/welcome': typeof WelcomeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/executive'
    | '/graph'
    | '/profile'
    | '/quantum'
    | '/response'
    | '/stories'
    | '/welcome'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/executive'
    | '/graph'
    | '/profile'
    | '/quantum'
    | '/response'
    | '/stories'
    | '/welcome'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/executive'
    | '/graph'
    | '/profile'
    | '/quantum'
    | '/response'
    | '/stories'
    | '/welcome'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ExecutiveRoute: typeof ExecutiveRoute
  GraphRoute: typeof GraphRoute
  ProfileRoute: typeof ProfileRoute
  QuantumRoute: typeof QuantumRoute
  ResponseRoute: typeof ResponseRoute
  StoriesRoute: typeof StoriesRoute
  WelcomeRoute: typeof WelcomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/response': {
      id: '/response'
      path: '/response'
      fullPath: '/response'
      preLoaderRoute: typeof ResponseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quantum': {
      id: '/quantum'
      path: '/quantum'
      fullPath: '/quantum'
      preLoaderRoute: typeof QuantumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph': {
      id: '/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/executive': {
      id: '/executive'
      path: '/executive'
      fullPath: '/executive'
      preLoaderRoute: typeof ExecutiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ExecutiveRoute: ExecutiveRoute,
  GraphRoute: GraphRoute,
  ProfileRoute: ProfileRoute,
  QuantumRoute: QuantumRoute,
  ResponseRoute: ResponseRoute,
  StoriesRoute: StoriesRoute,
  WelcomeRoute: WelcomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
